"""
Compare two evaluation snapshots (Person 5).

Diffs the headline metrics from ``report_v1.json`` (pre-Person-3 baseline)
against ``report_v2.json`` (post-Person-3 integration) and writes a
markdown delta table suitable for slide 16 of the final deck.

Usage::

    python scripts/compare_reports.py
    python scripts/compare_reports.py \
        --v1 tests/evaluation/report_v1.json \
        --v2 tests/evaluation/report_v2.json \
        --output tests/evaluation/report_v1_vs_v2.md
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_V1 = ROOT / "tests" / "evaluation" / "report_v1.json"
DEFAULT_V2 = ROOT / "tests" / "evaluation" / "report_v2.json"
DEFAULT_OUT = ROOT / "tests" / "evaluation" / "report_v1_vs_v2.md"


METRICS: list[tuple[str, str, str]] = [
    # (key in summary, display label, format spec)
    ("total", "Total cases", "{:d}"),
    ("passed", "Passed", "{:d}"),
    ("failed", "Failed", "{:d}"),
    ("pass_rate", "Pass rate", "{:.0%}"),
    ("intent_accuracy", "Intent accuracy", "{:.0%}"),
    ("escalation_precision", "Escalation precision", "{:.0%}"),
    ("escalation_recall", "Escalation recall", "{:.0%}"),
    ("false_escalation_rate", "False escalation rate", "{:.0%}"),
    ("avg_quality_score", "Avg quality score", "{:.2f}"),
    ("avg_response_confidence", "Avg response confidence", "{:.2f}"),
    ("avg_latency_ms", "Avg latency (ms)", "{:.2f}"),
    ("errors", "Errors", "{:d}"),
]


def _fmt(value: Any, spec: str) -> str:
    if value is None:
        return "n/a"
    try:
        return spec.format(value)
    except (ValueError, TypeError):
        return str(value)


def _delta(v1: Any, v2: Any) -> str:
    if v1 is None or v2 is None:
        return ""
    try:
        diff = float(v2) - float(v1)
    except (ValueError, TypeError):
        return ""
    if abs(diff) < 1e-9:
        return "no change"
    arrow = "↑" if diff > 0 else "↓"
    return f"{arrow} {abs(diff):.2f}"


def render(v1: dict[str, Any], v2: dict[str, Any]) -> str:
    s1 = v1["summary"]
    s2 = v2["summary"]
    lines: list[str] = []
    lines.append("# Pre / Post Person 3 — Evaluation Delta")
    lines.append("")
    lines.append("Snapshot comparison generated by `scripts/compare_reports.py`.")
    lines.append("")
    lines.append("| Metric | v1 (mock data) | v2 (with Person 3 data) | Delta |")
    lines.append("|--------|--------------:|------------------------:|-------|")
    for key, label, spec in METRICS:
        v1_val = s1.get(key)
        v2_val = s2.get(key)
        lines.append(f"| {label} | {_fmt(v1_val, spec)} | {_fmt(v2_val, spec)} | {_delta(v1_val, v2_val)} |")
    lines.append("")
    lines.append("## Band distribution")
    lines.append("")
    lines.append("| Band | v1 | v2 |")
    lines.append("|------|---:|---:|")
    bands = sorted(set(s1.get("band_distribution", {}).keys()) | set(s2.get("band_distribution", {}).keys()))
    for band in bands:
        lines.append(f"| {band} | {s1.get('band_distribution', {}).get(band, 0)} | {s2.get('band_distribution', {}).get(band, 0)} |")
    lines.append("")
    lines.append("## Pass rate by category")
    lines.append("")
    lines.append("| Category | v1 | v2 |")
    lines.append("|----------|---:|---:|")
    cats = sorted(set(s1.get("by_category", {}).keys()) | set(s2.get("by_category", {}).keys()))
    for cat in cats:
        b1 = s1.get("by_category", {}).get(cat, {"passed": 0, "total": 0})
        b2 = s2.get("by_category", {}).get(cat, {"passed": 0, "total": 0})
        v1_str = f"{b1['passed']}/{b1['total']}" if b1["total"] else "0/0"
        v2_str = f"{b2['passed']}/{b2['total']}" if b2["total"] else "0/0"
        lines.append(f"| {cat} | {v1_str} | {v2_str} |")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Compare two evaluation snapshots.")
    parser.add_argument("--v1", type=Path, default=DEFAULT_V1, help="Baseline snapshot")
    parser.add_argument("--v2", type=Path, default=DEFAULT_V2, help="Post-handoff snapshot")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUT, help="Markdown output path")
    args = parser.parse_args(argv)

    if not args.v1.exists():
        raise SystemExit(f"Baseline {args.v1} missing — run run_evaluation first.")
    if not args.v2.exists():
        raise SystemExit(
            f"v2 snapshot {args.v2} missing — run `python -m tests.evaluation.run_evaluation "
            f"--output {args.v2}` first."
        )

    v1 = json.loads(args.v1.read_text(encoding="utf-8"))
    v2 = json.loads(args.v2.read_text(encoding="utf-8"))
    md = render(v1, v2)
    args.output.write_text(md, encoding="utf-8")
    print(md)
    print(f"\nWrote comparison to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
